import type { LanguagePackDefinition } from "./types";

export const englishDemoPack = {
  pack: {
    id: "lang_en_us_v1",
    localeTag: "en-US",
    displayName: "English",
    nativeName: "English",
    direction: "ltr",
    version: "1.0.0",
    status: "active",
  },
  objectives: [
    {
      id: "obj_en_warmup",
      languagePackId: "lang_en_us_v1",
      slug: "tell-me-about-yourself",
      title: "Tell me about yourself",
      description: "Begin with a comfortable conversation about your background and interests.",
      prompt: "Tell me about yourself.",
      category: "warm_up",
      sequence: 1,
      estimatedMinutes: 8,
      isActive: true,
    },
    {
      id: "obj_en_narration",
      languagePackId: "lang_en_us_v1",
      slug: "narration-detail",
      title: "Narration & detail",
      description: "Practice sequencing, description, and context.",
      prompt: "Describe a time you helped a team navigate an unexpected change.",
      category: "narration",
      sequence: 2,
      estimatedMinutes: 12,
      isActive: true,
    },
    {
      id: "obj_en_opinion",
      languagePackId: "lang_en_us_v1",
      slug: "opinion-support",
      title: "Opinion & support",
      description: "State a position and develop it with examples.",
      prompt: "What makes communication effective across different cultures?",
      category: "opinion",
      sequence: 3,
      estimatedMinutes: 15,
      isActive: true,
    },
    {
      id: "obj_en_global_challenge",
      languagePackId: "lang_en_us_v1",
      slug: "global-leadership-challenge",
      title: "Global leadership challenge",
      description: "Explain a complex issue with a clear point of view.",
      prompt: "Explain a challenge facing global leaders today.",
      category: "extended_discourse",
      sequence: 4,
      estimatedMinutes: 15,
      isActive: true,
    },
  ],
  fluentExamples: [
    {
      id: "fluent_en_intro_01",
      languagePackId: "lang_en_us_v1",
      objectiveId: "obj_en_warmup",
      title: "A clear personal introduction",
      content: "I work in international education, where I help teams communicate across cultures. I enjoy making complex ideas easier to understand. Outside of work, I like exploring new places and learning from the people I meet.",
      coachingNote: "Notice how each sentence adds one clear layer: work, motivation, and personal interests.",
      audioStorageKey: null,
      sequence: 1,
    },
    {
      id: "fluent_en_change_01",
      languagePackId: "lang_en_us_v1",
      objectiveId: "obj_en_narration",
      title: "Clear change narrative",
      content: "When a project partner stepped away, I helped the team identify our priorities, clarify ownership, and establish short check-ins. That structure helped us deliver the essential work while preserving the relationship.",
      coachingNote: "Notice the clear situation, action, and result sequence.",
      audioStorageKey: null,
      sequence: 1,
    },
    {
      id: "fluent_en_culture_01",
      languagePackId: "lang_en_us_v1",
      objectiveId: "obj_en_opinion",
      title: "A supported point of view",
      content: "Effective communication across cultures begins with curiosity and careful listening. People need space to explain what they mean instead of assuming everyone shares the same expectations. Clear questions and respectful follow-up help a group build shared understanding.",
      coachingNote: "Listen for the position, explanation, and practical example.",
      audioStorageKey: null,
      sequence: 1,
    },
    {
      id: "fluent_en_leadership_01",
      languagePackId: "lang_en_us_v1",
      objectiveId: "obj_en_global_challenge",
      title: "A concise global perspective",
      content: "One challenge facing global leaders is making decisions when reliable information changes quickly. They must respond to immediate needs while considering how each decision affects different communities. Transparent communication can help people understand both the decision and the uncertainty behind it.",
      coachingNote: "Notice the problem, tension, and response structure.",
      audioStorageKey: null,
      sequence: 1,
    },
  ],
} as const satisfies LanguagePackDefinition;
